### ISSUE TITLE
Add support to Energy dashboard in home assistant

### ISSUE THREAD

**Issue by monsterciattolo** [alexdelprete/ha-abb-powerone-pvi-sunspec#10]
Hello,
is it possible to support new energy dashboard implemented in home assistant?

Thanks
Marcello

**Comment by alexdelprete** [comment]
Yes, new version will have the appropriate sensor attributes needed by the Energy dashboard. Check the thread for the first beta that needs testers. :)

**Comment by alexdelprete** [comment]
You might want to check this and join the other guys testing the latest beta: https://community.home-assistant.io/t/custom-component-abb-power-one-fimer-pv-inverters-sunspec-modbus-tcp/316363/58?u=alexdelprete

**Comment by monsterciattolo** [comment]
I tried the beta 2 but doesn't recognize both inverters.
I rolled back but I will provide some logs for troubleshooting later

**Comment by alexdelprete** [comment]
You need to be sure to set the right slave_id and the right offset, defaults might not be appropriate for your inverters.

**Comment by monsterciattolo** [comment]
I simply upgraded plugin without change any parameters.
With old version is working fine.

Here the error message with 2.0 beta2

Logger: homeassistant.config_entries
Source: custom_components/abb_powerone_pvi_sunspec/__init__.py:68
Integration: ABB Power-One PVI SunSpec (documentation, issues) 
First occurred: 13:33:56 (2 occurrences) 
Last logged: 13:33:56

Error setting up entry Inverter2 for abb_powerone_pvi_sunspec
Error setting up entry Inverter1 for abb_powerone_pvi_sunspec
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/abb_powerone_pvi_sunspec/__init__.py", line 68, in async_setup_entry
    base_addr = entry.data[CONF_BASE_ADDR]
KeyError: 'base_addr'

**Comment by alexdelprete** [comment]
You upgraded how? from which version to which version?

The config entries have changed, you need to delete the v1.x integration, then reinstall from HACS choosing beta version, then add the integration and on the configuration panel you need to set the base_address. If you simply upgrade from 1.x it won't work, because I introduced the 1.x base_address.

**Comment by alexdelprete** [comment]
Now the component works with the energy integration, fixed it in 2.0-beta4.

**Comment by monsterciattolo** [comment]
Great! 
I don't understand how find the slave_id using qmodmaster. Any guide available?

**Comment by alexdelprete** [comment]
The slave_id is the address of the inverter in the modbus chain. You can have multiple inverters in the same chain, each one has to have its own address. You can see the value from the inverter itself, if it has a display, or through ABB software that you are using.

With QmodMaster you input the slave_id, you can try 254 and see if it connects and reads registers, or try 2. It depends on the model. Check documentation or ABB software. to find it.

**Comment by alexdelprete** [comment]
Beta process is finished. v2.0.0 official has been released.

**Comment by monsterciattolo** [comment]
Issue resolved following your guide! Thanks

**Comment by alexdelprete** [comment]
> Issue resolved following your guide! Thanks

Where did you find the slave_id easily? So next time a user asks, I know what to tell them. :)

**Comment by monsterciattolo** [comment]
I used the old style method: I started from slave_id 2 to 3 and I was lucky!
One inverter is 2 and other is 3.

**Comment by alexdelprete** [comment]
ahahahahahah. Old school rulez! 👍🏽 

Probably the installer of your system left the first inverter at default (2) and when he added the second one, he increased by 1, correctly.

What inverter model is it? What offset address did you use, 40000? I need it as reference for other users. Thanks.

**Comment by monsterciattolo** [comment]
It's a VSN300 with fw 1.9.2.
I changed the offset to 0

In the past I used sunspec plugin.
It returns an error when parameters are incorrect but your plugin not.
Evaluate to add an error message to inform

**Comment by alexdelprete** [comment]
I'm using the VSN300 too. Offset for VSN300 is 0. For VSN700 (used on REACT2 inverters, it's 40000).

My component should write a line in the log when it reads from the inverter and it doesn't connect:

```
    def read_modbus_data(self):
        try:
            return self.read_modbus_data_inverter() and self.read_modbus_data_realtime()
        except ConnectionException as ex:
            _LOGGER.error("Reading data failed! Inverter is unreachable on ID=%s", self._slave_id)
            return True
```
