### ISSUE TITLE
ABB, UNO-DM-PLUS ETHERNET COM KIT

### ISSUE THREAD

**Issue by chrisandsally** [alexdelprete/ha-abb-powerone-pvi-sunspec#11]
Hi, I have an Aurora 3.0 UNO with a Lantronics 485 to IP converter which communicates to the windows software called Aurora Communicator.![Screenshot 2021-09-05 at 14 08 07](https://user-images.githubusercontent.com/89684974/132128139-1e8464a5-47e1-45c3-8f37-a468b8191e4f.png)
Will your integration work, If not will this card work?

**Comment by alexdelprete** [comment]
If it's Modbus Sunspec TCP, it should work. Personally, I chose the VSN300 datalogger, If you give me the exactl model number of your inverter I can check if the VSN300 is compatible.
