### ISSUE TITLE
Integration failed after IP changed (Unknown error occurred)

### ISSUE THREAD

**Issue by marcolinux46** [alexdelprete/ha-abb-powerone-pvi-sunspec#199]
### System Health details

Core
2024.12.3
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.8

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After IP changed the integration doesn't work, the sunspec integration is working fine

### Reproduction steps

1. Restart Integration
2. Delete Integration and created again

### Debug logs

```text
Registratore: aiohttp.server
Fonte: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
Prima occorrenza: 13 dicembre 2024 alle ore 16:11:28 (13 occorrenze)
Ultimo accesso: 15:32:40

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 112, in async_step_user
    uid = await self.test_connection(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        name, host, port, slave_id, base_addr, scan_interval
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 85, in test_connection
    self.api_data = await self.api.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 190, in async_get_data
    if self.connect():
       ~~~~~~~~~~~~^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 167, in connect
    raise ConnectionError(f"Inverter not active on {self._host}:{self._port}")
custom_components.abb_powerone_pvi_sunspec.api.ConnectionError: Inverter not active on xxx.xxx.xxx.xxx:502
```

**Comment by alexdelprete** [comment]
Sarebbe stato meglio il debug log, quello che hai fornito è l'errore del log standard di HA. Per fornire il debug log devi abilitare il debug sull'integrazione.

![image](https://github.com/user-attachments/assets/0aa8c0db-a7dc-4298-9e8d-45e05ce31b4f)

Da quello che hai riportato però il problema è chiaro: "Inverter not active on xxx.xxx.xxx.xxx:502"

Quando l'integrazione si collega, fa prima un check della disponibilità di ip e porta, se il test fallisce, restituisce quell'errore.

```python
        if self.check_port():
            _LOGGER.debug("Inverter ready for Modbus TCP connection")
            try:
                with self._lock:
                    self._client.connect()
                if not self._client.connected:
                    raise ConnectionError(
                        f"Failed to connect to {self._host}:{self._port} slave id {self._slave_id} timeout: {self._timeout}"
                    )
                else:
                    _LOGGER.debug("Modbus TCP Client connected")
                    return True
            except ModbusException:
                raise ConnectionError(
                    f"Failed to connect to {self._host}:{self._port} slave id {self._slave_id} timeout: {self._timeout}"
                )
        else:
            _LOGGER.debug("Inverter not ready for Modbus TCP connection")
            raise ConnectionError(f"Inverter not active on {self._host}:{self._port}")
```

**Comment by marcolinux46** [comment]
Ciao @alexdelprete ,

mi sembra strano che fallisca il controllo poiché con un'altra integrazione stessa porta e slave id funziona correttamente
![image](https://github.com/user-attachments/assets/f2ecea33-9f18-4505-8cf9-27b7753e31b3)

Bisogna pulire qualche file dentro HA?

**Comment by alexdelprete** [comment]
quella funzione di check è lì da 2 anni. funziona. tanto è vero che l'autore di sunspec l'ha adottata prendendola dalla mia integrazione.

disinstalla l'integrazione, riavvia HA, e reinstalla l'integrazione. accertati di usare l'IP corretto.

**Comment by marcolinux46** [comment]
@alexdelprete non mi fraintendere, la tua integrazione la sponsorizzo a chiunque abbia HA e un inverter ABB.
L'integrazione è già disinstallata, proverò a riavviare nuovamente HA.
L'ip purtroppo è corretto in quanto è quello utilizzato dall'integrazione di Sunspec.

Ti tengo aggiornato

Grazie mille

**Comment by marcolinux46** [comment]
Ho testato telnet da HA su porta 502... ok
Ho reinstallato l'integrazione susnspec e legge tutti i dati dall'inverter
Ho eliminato l'integrazione e riscaricata nuovamente da HACS
Riavviato HA

Purtroppo nulla

Il log che posso fornirti è solo quello di HA perchè il dispositivo non me lo fa creare e quindi non posso abilitare il log specifico come mi hai suggerito

Hai uno script per fare il check dell'inverter?

**Comment by alexdelprete** [comment]
> Il log che posso fornirti è solo quello di HA perchè il dispositivo non me lo fa creare

non capisco. mi fai vedere la schermata del device come da mio screenshot? vai in integrazioni e apri l'integrazione. fai screenshot e postala qui.

**Comment by marcolinux46** [comment]
@alexdelprete il dispositivo l'ho cancellato qualche giorno fa...
L'errore mi viene dato durante la creazione del device 
Più tardi ti mando gli screenshot

**Comment by alexdelprete** [comment]
ah ecco...durante la configurazione...

quale versione stai installando?

**Comment by marcolinux46** [comment]
3.5.0

**Comment by alexdelprete** [comment]
prova con altre release, per curiosità, anche se la parte di connessione non è stata modificata. Mett l'ultima beta, e prova anche l'ultima 3.4.x.

**Comment by marcolinux46** [comment]
Installata la 3.4.2 e la 3.5.1beta2 ma il problema persiste

![image](https://github.com/user-attachments/assets/7bce55d1-8621-4f02-a7f4-dcaeadaa5812)

![image](https://github.com/user-attachments/assets/b4384158-a180-41b6-94ae-a3f1ef9e0ac8)

Log sempre lo stesso, quindi evito di ripeterlo

**Comment by marcolinux46** [comment]
Grazie mille per il supporto.
Ora ho disinstallato il pacchetto e riavviato HA.
Proverò a reinstallarlo e vedere se funziona

Ti farò sapere

**Comment by marcolinux46** [comment]
@alexdelprete 
ieri ho eseguito le procedure del commento precedente ma senza successo.
Per scrupolo anche io ho installato una nuova istanza di HA ma continua lo stesso errore

![image](https://github.com/user-attachments/assets/9fc5b983-2d5a-42d1-9356-15800b4dbf19)

per completezza di informazioni utilizzo la versione HAOS

**Comment by marcolinux46** [comment]
Una domanda, quando fa il controllo invia una sorta di pacchetto unicast/multicast all'inverter?

**Comment by alexdelprete** [comment]
la funzione check_port() apre un socket...ti ho messo il codice sopra...se fallisce, vuol dire che non è disponibile. non è comunicazione multicast. hai un fw di mezzo? vlan e roba simile?

l'autore di sunspec, che conosco, nelle ultime versioni ha introdotto anche lui il check della porta perché ha incontrato gli stessi problemi che io risolsi tempo fa.

**Comment by alexdelprete** [comment]
> Nessun firewall e VLAN 1 Nessun VLAN routing La cosa particolare è che l'integrazione ha-sunspec funziona senza problemi

l'altra cosa particolare è che solo tu hai lamentato questo problema. :)

**Comment by marcolinux46** [comment]
Ovviamente ci deve essere sempre l'eccezione che conferma la regola. :)
Ho fatto la prova con una nuova installazione per capire se fosse un problema del mio HA

**Comment by alexdelprete** [comment]
Allora, l'autore di sunspec ha copiato esattamente il codice per il check_port() che uso io, puoi vedere tu stesso:

Il mio:
https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/blob/e4d07ca691c849cbfc9519f1aa8cef929c1851d3/custom_components/abb_powerone_pvi_sunspec/api.py#L107

Il suo:
https://github.com/CJNE/ha-sunspec/blob/8ac104d4504ed497323edeaf44e2ceb2b32f78b2/custom_components/sunspec/api.py#L159

**Comment by marcolinux46** [comment]
Ecco perchè mi fa più strano il diverso funzionamento.
Nel log però vedo come se l'errore partisse da una differenza di invio di dati alla funzione read_sunspec_modbus_model_1

Traceback (most recent call last):
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 223, in read_sunspec_modbus
    self.read_sunspec_modbus_model_1()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 322, in read_sunspec_modbus_model_1
    read_model_1_data = self.read_holding_registers(
        slave=self._slave_id, address=(self._base_addr + 70), count=40
    )
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 174, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModbusClientMixin.read_holding_registers() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

**Comment by marcolinux46** [comment]
Mancanza del mio HA di qualche libreria?

**Comment by alexdelprete** [comment]
Mi stai dando log che non hanno senso, lì sta facendo una lettura...quindi si è connesso. Boh...senza debug log mi spiace ma non so come aiutarti. Questo ultimo log è diverso dagli altri che mi hai dato, quella è una fase di lettura dei registri. Che versione è?

**Comment by marcolinux46** [comment]
Cerco di spiegarmi bene.
Nel mio HA non ho più nessun dispositivo configurato.
Quando provo a configurare un nuovo dispositivo l'unico log che ho è dentro la sezione LOG di HA e recita quanto segue:

Registratore: aiohttp.server
Fonte: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
Prima occorrenza: 15:53:44 (1 occorrenze)
Ultimo accesso: 15:53:44

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 222, in read_sunspec_modbus
    self.read_sunspec_modbus_model_1()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 243, in read_sunspec_modbus_model_1
    read_model_1_data = self.read_holding_registers(
        slave=self._slave_id, address=(self._base_addr + 4), count=64
    )
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 174, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModbusClientMixin.read_holding_registers() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 112, in async_step_user
    uid = await self.test_connection(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        name, host, port, slave_id, base_addr, scan_interval
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 85, in test_connection
    self.api_data = await self.api.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 198, in async_get_data
    result = await self._hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.read_sunspec_modbus
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 230, in read_sunspec_modbus
    raise ModbusError() from modbus_error
custom_components.abb_powerone_pvi_sunspec.api.ModbusError

**Comment by marcolinux46** [comment]
@alexdelprete 
Problema risolto....
Tutto quanto nasceva dal valore del Modbus Address.
Io mettevo 0 ma invece non mi ricordavo che andava messo 40000 (scoperto attraverso un piccolo script in python e le librerie modbus)

Grazie mille per il supporto

Questo conferma la validità della tua integrazione....

**Comment by alexdelprete** [comment]
> Io mettevo 0 ma invece non mi ricordavo che andava messo 40000 (scoperto attraverso un piccolo script in python e le librerie modbus)

1. Avevi detto di aver cambiato solo l'ip. :)
2. Bastava leggere il readme dell'integrazione:

![image](https://github.com/user-attachments/assets/83683e2e-91b4-43cf-8ac4-bf3b3fc7043d)

**Comment by marcolinux46** [comment]
In realtà sull'inverter ho cambiato solo IP.
Il problema è nato quando ho ricreato il dispositivo su HA.

Purtroppo non mi ricordavo che il base address fosse 40000 (alle volte i README servono :) )

Scusa il disturbo e grazie mille per il supporto

**Comment by alexdelprete** [comment]
> In realtà sull'inverter ho cambiato solo IP.
> Il problema è nato quando ho ricreato il dispositivo su HA.

Nessuno legge i readme a dovere...
Consiglio sempre di usare gli hostname, in FQDN, così non devi smanettare quando cambi IP.

![image](https://github.com/user-attachments/assets/81b6af84-a1ea-4b9e-8361-c3df24580c32)

**Comment by marcolinux46** [comment]
Di solito leggo i readme e sull'indirizzo del modbus ero straconvinto fosse 0

Sto cercando di portare tutto a fqdn così da non dover diventare più matto
