### ISSUE TITLE
Entities unavailable after upgrade to V.2.0.0

### ISSUE THREAD

**Issue by bkoneski** [alexdelprete/ha-abb-powerone-pvi-sunspec#20]
Hi,

Big improvements in this new version! was waiting for some of them! Thanks! 
however I am having issues after upgrading to V.2.0.0

V1.2.1 - OK
V.2.0.0 - NOK
for tested, I tried a downgrade to 1.2.1 and it started working again!

home-assistant.log:
```log
2021-09-10 12:32:48 ERROR (MainThread) [custom_components.abb_powerone_pvi_sunspec] Reading data failed! Inverter is unreachable on ID=247
2021-09-10 12:32:48 ERROR (MainThread) [custom_components.abb_powerone_pvi_sunspec] Reading data failed! Inverter is unreachable on ID=247
2021-09-10 12:32:48 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up abb_powerone_pvi_sunspec platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/abb_powerone_pvi_sunspec/sensor.py", line 25, in async_setup_entry
    "model": hub.data["comm_model"],
KeyError: 'comm_model'
```

**Inverter : UNO-3.0-TL-OUTD + VSN300**

## System Health

version | core-2021.9.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/Sao_Paulo

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4461
Installed Version | 1.15.2
Stage | running
Available Repositories | 881
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.3
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 57.8 GB
disk_used | 6.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | eWeLink Smart Home (1.2.0), File editor (5.3.3), Terminal & SSH (9.1.3), ESPHome (2021.8.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 10
views | 3
mode | storage

</details>

Thanks,
Bruno

**Comment by alexdelprete** [comment]
Sorry for the late reply Bruno. I hope you solved it meanwhile.

The error is clear: `Reading data failed! Inverter is unreachable on ID=247`

Are you sure the ID of the inverter is 247?
