### ISSUE TITLE
Model unknown

### ISSUE THREAD

**Issue by asvel78** [alexdelprete/ha-abb-powerone-pvi-sunspec#54]
Hi Alessandro, 

I receive this message in the logs

Model unknown, report to @alexdelprete on the forum the following data: Manuf.: ABB - Model: -3P38- - Options: 0x0BED/0xFF69/ - OptModel: 0x0BED/0xFF69/

my Model: UNO-DM-2.0-TL-PLUS

Regards.
LN

**Comment by alexdelprete** [comment]
Hi,

there's a missing piece (`OptModelInt`) at the end of the logged line, should be something like this:

`Options: 0x10ED/0xFF69/ - OptModel: 0x10ED/0xFF69/ - OptModelInt: 16`

Could you paste the complete line here? I will add your model to the source, and in next release your model# will be correctly reported.

Thanks.

**Comment by alexdelprete** [comment]
No problem, it happens. :)

I just released v2.6.1, thanks for your report.

If you now see the correct model in the sensor, please close the issue.

**Comment by asvel78** [comment]
Solved, thanks Alex
