### ISSUE TITLE
Lost of data readings after one day

### ISSUE THREAD

**Issue by anxdroid** [alexdelprete/ha-abb-powerone-pvi-sunspec#68]
Buonasera,

I have installed your plugin via HACS on a venv installation of HA core on RPI 4. Everything is working fine with my PVI-3.0-OUTD and I can access all sensor data. The problem is that every day/couple of days the integration stops reading data and I have to re-configure it (I just click "INVIA") to have it work again. It is important to notice that I restart HA through an automation every night. Can it be related ? Can I automate this step to force reload configuration after HA restart ?

Grazie
<img width="880" alt="Screenshot 2023-07-03 alle 21 40 43" src="https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/8686353/386d6374-1cf6-438b-9778-633a08383331">
<img width="348" alt="Screenshot 2023-07-03 alle 21 34 30" src="https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/8686353/a13dabbe-52be-4b90-a5c7-ca1cae76dbaf">
<img width="835" alt="Screenshot 2023-07-03 alle 21 33 02" src="https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/8686353/15a4e8a7-a061-47e7-ae22-154a9f6bfda9">

**Comment by alexdelprete** [comment]
Ciao Antonello,

I replied to your post on the forum 11 days ago: https://community.home-assistant.io/t/custom-component-abb-power-one-fimer-pv-inverters-sunspec-modbus-tcp/316363/287?u=alexdelprete
