### ISSUE TITLE
Integration Error after HA Update

### ISSUE THREAD

**Issue by marcolinux46** [alexdelprete/ha-abb-powerone-pvi-sunspec#70]
Hi @alexdelprete ,

after last HA update i have the following error on log window about the integration.

`Logger: custom_components.abb_powerone_pvi_sunspec
Source: custom_components/abb_powerone_pvi_sunspec/__init__.py:228
Integration: ABB Power-One PVI SunSpec ([documentation](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec), [issues](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/issues))
First occurred: 05:32:57 (1 occurrences)
Last logged: 05:32:57

(read_data) Error: check Slave ID: 1 & Base Address: 40000`

Until this update everything worked fine

Can you help me to resolve this issue?

Thank you for your support

HA Running Information:

Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest

**Comment by naamah75** [comment]
Same problem here

**Comment by woodrook** [comment]
Same here :(

**Comment by alexdelprete** [comment]
I upgraded to 2023.9 and I don't see this error.

**Comment by woodrook** [comment]
I just tryed to remove the integration and reinstall with the same settings..........it show "no device or entities"

Before the 2023.9 upgrade everything was perferct

**Comment by alexdelprete** [comment]
![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/6f2c2649-da2f-435d-9dce-cad7b9d597eb)
![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/b818a911-9264-4082-a303-79adc8728e27)

**Comment by marcolinux46** [comment]
![Screenshot_2023-09-08-14-55-17-765_io homeassistant companion android](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/ec979b24-212a-4f44-b5b0-10cd399ed6a3)

**Comment by NicolasFOVET** [comment]
Hi, same issue for me, integration indicates inverter not available since I upgraded to 2023.9.0.

**Comment by woodrook** [comment]
Solved! I’ve manually deleted abb integration and manually installed a new one. Configuration has been made from the mobile phone app instead od a computer browser.
Now everything seems to work. Keep finger crossed

**Comment by marcolinux46** [comment]
I did the same but nothing change
Now i have no device or entity

**Comment by marcolinux46** [comment]
Reconfigured now.... 
Same error

**Comment by alexdelprete** [comment]
Nothing changed in 2023.9.0 that impacts the integration (pymodbus etc.). It's working fine here.

Make sure the IP is reachable (the VSN card) and that slave id and base address are ok.

**Comment by marcolinux46** [comment]
@alexdelprete 
The ip is reachable and i checked the slave id and base address directly on inverter
Everything is ok
Nothing working after HA update
Before update the integration was good always perfect

**Comment by marcolinux46** [comment]
I also test the TCP modbus with modpoll client
And i see all the data

**Comment by marcolinux46** [comment]
I have also the Cnje/sunspec integration. 
Same issue... 
I left and reconfigured it and now is working

**Comment by alexdelprete** [comment]
> I left and reconfigured it and now is working

what is working?

ANd also, tell me, what's this stuff highlighted in the red box?

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/e92a40ae-b70d-46ce-b37b-a216ebb686e3)

**Comment by marcolinux46** [comment]
@alexdelprete 

Now is working the Cjne/ha-sunspec integration. 
Your integration is still off. 

In the red box there are two consumption control but now are disabled.

**Comment by marcolinux46** [comment]
Can i do some checks from ha?

**Comment by alexdelprete** [comment]
> In the red box there are two consumption control but now are disabled.

So you modified the code? Reinstall the component from scratch. And also, post the entire HA log so we can check if you have other errors too.

**Comment by marcolinux46** [comment]
No i don't modify the code
They are simple Riemann helpers
I try to reinstall from scratch

**Comment by alexdelprete** [comment]
> I also test the TCP modbus with modpoll client And i see all the data

from where are you testing TCP modbus? how is HA installed? docker...bare metal...you need to test TCP modbus connection from the same instance HA is running, not only from your pc.

**Comment by marcolinux46** [comment]
HA is installed on a VM
I can make some tests from terminal

**Comment by alexdelprete** [comment]
> HA is installed on a VM
> I can make some tests from terminal

from the VM, check basic ping first, then Modbus TCP. The error is clear: it can't contact the VSN card.

**Comment by marcolinux46** [comment]
Basic ping is working
How can i test modbus TCP?

**Comment by marcolinux46** [comment]
I installed integration from scratch again 
Seems to be no errore occured

**Comment by alexdelprete** [comment]
> I installed integration from scratch again Seems to be no errore occured

So it's working?

**Comment by marcolinux46** [comment]
Nop

**Comment by marcolinux46** [comment]
When i install the integration pack
But when i configure the inverter not working

**Comment by alexdelprete** [comment]
setup a test HA instance from scratch (if you have a docker VM), and install from there to test.

**Comment by marcolinux46** [comment]
Probably i understand the problem. 
Inside the integration folder is missing some files. 
Later i will install the package manually and i will let you know

**Comment by alexdelprete** [comment]
> Probably i understand the problem. Inside the integration folder is missing some files. Later i will install the package manually and i will let you know

If you reinstalled from scratch, how can there be missing files?

Also, try the "redownload" option of HACS: open the component page from HACS and in the upper right, click the three dots and redownload. It will install all the files again.

If you're missing files, you have something not working correctly.

**Comment by marcolinux46** [comment]
I removed the integration from HACS and i reinstalled it
This is what i see
![file_abb](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/efc09c8c-b491-4492-ba1c-7b6434209753)

Now i try to upload all the files and i let you know

**Comment by marcolinux46** [comment]
Resolved.....
Files missing on integration folder after update
Problably something wrong with HACS

Thank you all for support
