### ISSUE TITLE
New Inverter Model

### ISSUE THREAD

**Issue by marcolinux46** [alexdelprete/ha-abb-powerone-pvi-sunspec#71]
@alexdelprete 

Can you update the model list? 

Logger: custom_components.abb_powerone_pvi_sunspec
Source: custom_components/abb_powerone_pvi_sunspec/api.py:134
Integration: ABB/Power-One/FIMER PVI SunSpec (documentation, issues)
First occurred: 18:52:01 (116 occurrences)
Last logged: 19:48:31

(opt_comm_model) Model unknown, report to @alexdelprete on the forum the following data: Manuf.: ABB - Model: -3P21- - Options: 0x00ED/0xFF69/ - OptModel: 0x00ED/0xFF69/ - OptModelInt: 0

My model is UNO-DM-3.3-TL-PLUS

Thank you

**Comment by alexdelprete** [comment]
Ok, I'll add it. You'll have to wait for next release to see the change.

NB: 0x00ED represents model id + family id. 00 is a bit strange as model id, ED is correct for family id.
