### ISSUE TITLE
Update Problem (file missing)

### ISSUE THREAD

**Issue by marcolinux46** [alexdelprete/ha-abb-powerone-pvi-sunspec#73]
@alexdelprete 

there's something wrong with HACS update process.
Today i update your integration to 2.6.7 via HACS and it is not working again.

This is the folder before update

![pre_update](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/2760bbb7-c2b7-4d23-9261-7bead138fc21)

and this is after update

![post_update](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/95496147-5d5f-4d4b-857b-906446398a34)

Now i try to reload the file manually as yesterday

Thank you for your support

**Comment by marcolinux46** [comment]
Integration Manually Installed

![connection_failed](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/0988fbd9-7333-49d6-999b-e7d44dec71d3)

**Comment by alexdelprete** [comment]
You are confusing things: there's a master branch

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/9aaf4071-f8da-4cc0-850d-6d28b4f82932)

And there's the official release branch, tagged with the version (v2.6.7):

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/2fc360e0-d83a-485c-bdac-5eb2528f700d)

Don't upload manually if you don't understand that there are different branches, and always use the tagged release version. The master branch is my dev branch, and I experiment things, etc.

Use HACS when redownloading, and don't choose master from there, only choose the numbered versions.

**Comment by marcolinux46** [comment]
@alexdelprete 

i chose the numbered release from HACS and now i have this file on integration folder

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/1daa13d2-7a74-4c57-bfd4-c2a5538438a2)

when i try to configure my inverter i receive this error on log again
(This issue is starting from 2023.9.0 HA update)

"Logger: custom_components.abb_powerone_pvi_sunspec
Source: custom_components/abb_powerone_pvi_sunspec/__init__.py:228
Integration: ABB Power-One PVI SunSpec (documentation, issues)
First occurred: 17:59:20 (3 occurrences)
Last logged: 17:59:33

(read_data) Error: check Slave ID: 1 & Base Address: 40000"

Thanks

**Comment by alexdelprete** [comment]
> i chose the numbered release from HACS and now i have this file on integration folder

Ciao Marco, I found the problem, see release notes of latest v2.6.8 please.

Let me know if 2.6.8 works for you, thanks.

**Comment by marcolinux46** [comment]
Ciao Alex, 

Tomorrow morning i will do some tests and i will let you know

Thanks

**Comment by alexdelprete** [comment]
I managed to do one test right before the inverter shut off...only 2 minutes unfortunately. And it worked. Let me know...

**Comment by marcolinux46** [comment]
Here i am,

1 - Inverter Up and Running (PING and NMAP OK)
2 - Removed all the old integration instances from HACS
3 - Installed from scratch, through HACS, version 2.6.8 integration package directly
4 - Installed the inverter --- Not Working ---

below are the results

Files on folder

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/f4395a0b-3bc8-45b6-b0c3-a60981132bb2)

Manifest.json

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/76199111-8aaa-4261-bb68-28ead02f8656)

Service and Device

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/9926a5b3-bf53-49ef-bd0b-706d04851d8e)

System LOG

Logger: custom_components.abb_powerone_pvi_sunspec
Source: custom_components/abb_powerone_pvi_sunspec/__init__.py:228
Integration: ABB Power-One PVI SunSpec ([documentation](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec), [issues](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/issues))
First occurred: 07:24:53 (3 occurrences)
Last logged: 07:25:06

(read_data) Error: check Slave ID: 1 & Base Address: 40000

Is there anything I can do to help you?

Thanks

**Comment by naamah75** [comment]
Same issue as @marcolinux46

**Comment by alexdelprete** [comment]
> Same issue as @marcolinux46

Thanks for the updates guys: I'm in contact with other devs of other inverter's components, they're all having problems with latest pymodbus versions, it seems there's more than one problem. The one I caught yesterday was blocking, but it seems there's a problem with the connect() function.

From what I read, HA 2023.9.2 will be released soon with a new pymodbus version (3.6 I guess) which should contain some fixes.

Stay tuned...

**Comment by alexdelprete** [comment]
@marcolinux46 @naamah75 Guys, can you please try the master branch? You can redownload from HACS, and when the list of versions comes up, scroll down to the bottom and you'll see `master`.

Double-check that in the component's folder you have the following files, then restart and let me know how it goes. Thanks.

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/37b1af06-a9f1-464d-bc68-17eee45a6b0c)

**Comment by marcolinux46** [comment]
Here i am,

this is the version....same as yours:

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/c643b4fd-52dc-408f-9c7d-e18b7136069f)

this is the content integration folder:

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/eb787919-98c1-455a-b699-49997deba2c9)

And this is the final result:

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/fc2402c4-1b4b-4bbd-90a5-efc57815da42)

Yesssssssssssssssssssssssssss

Good job @alexdelprete

**Comment by alexdelprete** [comment]
That's awesome! :)

Thanks Marco. I didn't want to release this version because it's totally different and was a WIP since a couple of months. But I guess I'll have to introduce it sooner than I expected. It's still not tested properly yet...let's cross fingers. :)

**Comment by marcolinux46** [comment]
No problem Alex,

I check the server every day, if I find any problems I will let you know.
For the moment i don't see the right model yet, but i thing thi is because is master branch.

Thank you for your support

**Comment by alexdelprete** [comment]
> I check the server every day, if I find any problems I will let you know. For the moment i don't see the right model yet, but i thing thi is because is master branch.

Damn it, I forgot your model and I just released v3.0.0. :(

When you install v3.0.0, modify const.py, lines 204-205:

```python
DEVICE_MODEL = {
      0: "UNO-DM-3.3-TL-PLUS",
```

Basically you need to add the 0: line. Then wait for v3.0.1.

**Comment by marcolinux46** [comment]
Ahahahahahaha no worry about it,

Update to 3.0.0 Major release and it seems working fine and device model too.

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/65719155/f6a12734-7376-402c-8e41-1b8d136056c0)

Good job @alexdelprete 

I will update during this period if some issues occur.

Have a good weekend

**Comment by alexdelprete** [comment]
> Same issue as @marcolinux46

@naamah75 did you try v3.0.0? Is it working for you?

**Comment by naamah75** [comment]
> 

Yes! it work! thanks!

**Comment by alexdelprete** [comment]
@marcolinux46 @naamah75 please test beta.5. I'm testing it since 24h without disabling the integration or any external automation. The solution was to test if Modbus TCP was available at socket level before trying the modbus connect (pymodbus call). This avoids all the errors etc. The retry mechanism is managed by HA itself, and the integration will be online automatically as soon as the TCP port is available (inverter on) and the Modbus TCP connect is processed correctly.

**Comment by marcolinux46** [comment]
@alexdelprete i installed the beta.5 and everythink is working fine.
No problem for now.

**Comment by naamah75** [comment]
@alexdelprete ... installed b5, now it works. I will keep an eye on it during the day.

**Comment by alexdelprete** [comment]
I tested it for 2 days, it's working fine here when inverter powers off and on, etc. No log spamming either. I released v3.1.0 final based on this.

Let me know how it goes...thanks for the help.

**Comment by marcolinux46** [comment]
@alexdelprete installed now 3.1.0
No problem during installation and no error or warning on log. 

If something happens i will let you know

Thanks

**Comment by alexdelprete** [comment]
> installed now 3.1.0

Just released 3.1.1 with a minor improvement. But it shouldn't affect you, install it when you can.
